CREATE TABLE AccountPacketFact (
    packet_id VARCHAR(255) NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    client_name VARCHAR(512),
    household_id VARCHAR(255),
    custodian_id VARCHAR(255) NOT NULL,
    custodian_name VARCHAR(255),
    form_id VARCHAR(255),
    form_template_name VARCHAR(255),
    account_type VARCHAR(255),
    submission_timestamp TIMESTAMP NOT NULL,
    ingestion_timestamp TIMESTAMP,
    validated_status VARCHAR(32) NOT NULL,
    packet_status VARCHAR(32) NOT NULL,
    error_flag BOOLEAN DEFAULT FALSE,
    source_file VARCHAR(1024),
    validation_timestamp TIMESTAMP,
    packet_assembly_timestamp TIMESTAMP,
    doc_prep_timestamp TIMESTAMP,
    exception_flag BOOLEAN DEFAULT FALSE,
    exception_type VARCHAR(255),
    required_documents_json JSON,
    submitted_documents_json JSON,
    form_fields_json JSON NOT NULL,
    supporting_documents_json JSON,
    reviewer_id VARCHAR(255),
    reviewer_decision VARCHAR(64),
    reviewer_notes VARCHAR(1024),
    review_timestamp TIMESTAMP,
    workflow_state VARCHAR(64),
    workflow_status VARCHAR(64),
    workflow_event_id VARCHAR(255),
    linked_envelope_id VARCHAR(255),
    envelope_status VARCHAR(32),
    envelope_routing_timestamp TIMESTAMP,
    doc_link VARCHAR(1024),
    status_update_json JSON,
    writeback_id VARCHAR(255),
    writeback_status_code VARCHAR(64),
    writeback_synctimestamp TIMESTAMP,
    packet_metadata_json JSON,
    audit_event_id VARCHAR(255),
    audit_event_timestamp TIMESTAMP,
    audit_actor_id VARCHAR(255),
    audit_event_type VARCHAR(128),
    audit_metadata_json JSON,
    lineage_reference_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (packet_id, submission_timestamp)
)

CREATE TABLE WorkflowStateFact (
    workflow_event_id VARCHAR(255) NOT NULL,
    packet_id VARCHAR(255) NOT NULL,
    state_transition VARCHAR(64) NOT NULL,
    previous_state VARCHAR(64),
    next_state VARCHAR(64),
    event_type VARCHAR(128),
    exception_flag BOOLEAN DEFAULT FALSE,
    exception_type VARCHAR(255),
    reviewer_id VARCHAR(255),
    reviewer_decision VARCHAR(64),
    reviewer_notes VARCHAR(1024),
    event_timestamp TIMESTAMP NOT NULL,
    event_metadata_json JSON,
    workflow_actor_id VARCHAR(255),
    process_step VARCHAR(128),
    related_form_id VARCHAR(255),
    related_document_id VARCHAR(255),
    related_envelope_id VARCHAR(255),
    workflow_notes VARCHAR(2048),
    human_in_loop BOOLEAN DEFAULT FALSE,
    escalation_flag BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (workflow_event_id, event_timestamp)
)

CREATE TABLE SignatureEnvelopeFact (
    envelope_id VARCHAR(255) NOT NULL,
    packet_id VARCHAR(255) NOT NULL,
    envelope_status VARCHAR(32) NOT NULL,
    doc_link VARCHAR(1024),
    envelope_template_name VARCHAR(255),
    envelope_type VARCHAR(64),
    envelope_event_timestamp TIMESTAMP NOT NULL,
    recipient_email VARCHAR(512),
    recipient_role VARCHAR(255),
    routing_order INTEGER,
    signature_required BOOLEAN DEFAULT TRUE,
    signed_timestamp TIMESTAMP,
    envelope_metadata_json JSON,
    source_system VARCHAR(255),
    form_id VARCHAR(255),
    associated_document_ids_json JSON,
    routing_status_json JSON,
    error_flag BOOLEAN DEFAULT FALSE,
    error_message VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (envelope_id, envelope_event_timestamp)
)

CREATE TABLE WritebackStatusFact (
    writeback_id VARCHAR(255) NOT NULL,
    packet_id VARCHAR(255) NOT NULL,
    status_code VARCHAR(64) NOT NULL,
    synctimestamp TIMESTAMP NOT NULL,
    writeback_type VARCHAR(64),
    target_system VARCHAR(255),
    writeback_payload_json JSON,
    previous_status_code VARCHAR(64),
    related_form_id VARCHAR(255),
    related_envelope_id VARCHAR(255),
    writeback_status VARCHAR(64),
    writeback_event_timestamp TIMESTAMP,
    writeback_error_code VARCHAR(128),
    writeback_error_message VARCHAR(1024),
    writeback_actor_id VARCHAR(255),
    writeback_notes VARCHAR(2048),
    workflow_state_at_writeback VARCHAR(64),
    writeback_metadata_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (writeback_id, synctimestamp)
)

CREATE TABLE AuditEventFact (
    audit_event_id VARCHAR(255) NOT NULL,
    packet_id VARCHAR(255),
    event_type VARCHAR(128) NOT NULL,
    event_timestamp TIMESTAMP NOT NULL,
    actor_id VARCHAR(255),
    event_result VARCHAR(128),
    event_notes VARCHAR(2048),
    related_form_id VARCHAR(255),
    related_document_id VARCHAR(255),
    related_envelope_id VARCHAR(255),
    source_system VARCHAR(255),
    audit_metadata_json JSON,
    exception_flag BOOLEAN DEFAULT FALSE,
    exception_type VARCHAR(255),
    escalation_flag BOOLEAN DEFAULT FALSE,
    lineage_reference_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (audit_event_id, event_timestamp)
)

CREATE TABLE Client_Dimension (
    client_id VARCHAR(255) NOT NULL,
    client_name VARCHAR(512),
    household_id VARCHAR(255),
    client_type VARCHAR(128),
    client_status VARCHAR(64),
    onboarding_status VARCHAR(64),
    email_address VARCHAR(512),
    phone_number VARCHAR(64),
    primary_contact VARCHAR(255),
    mailing_address VARCHAR(1024),
    city VARCHAR(128),
    state VARCHAR(64),
    zipcode VARCHAR(32),
    country VARCHAR(64),
    account_count INTEGER,
    last_onboarding_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata_json JSON,
    effective_date DATE,
    expiry_date DATE,
    PRIMARY KEY (client_id)
)

CREATE TABLE Custodian_Dimension (
    custodian_id VARCHAR(255) NOT NULL,
    custodian_name VARCHAR(255),
    custodian_type VARCHAR(128),
    form_id VARCHAR(255),
    form_template_name VARCHAR(255),
    account_type VARCHAR(255),
    custodian_address VARCHAR(1024),
    custodian_contact VARCHAR(255),
    phone_number VARCHAR(64),
    email_address VARCHAR(512),
    version VARCHAR(64),
    ingest_timestamp TIMESTAMP,
    source_system VARCHAR(255),
    metadata_json JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    effective_date DATE,
    expiry_date DATE,
    PRIMARY KEY (custodian_id, form_id, account_type)
)

CREATE TABLE Envelope_Dimension (
    envelope_id VARCHAR(255) NOT NULL,
    envelope_template_name VARCHAR(255),
    envelope_type VARCHAR(64),
    doc_type VARCHAR(128),
    description VARCHAR(1024),
    version VARCHAR(64),
    template_status VARCHAR(32),
    envelope_metadata_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    effective_date DATE,
    expiry_date DATE,
    PRIMARY KEY (envelope_id)
)